version: '3.3'

services:
  db: #Container de MySQL
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  wordpress:
    depends_on:
      - db 
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - "C:\\Volumes:/var/www/html"
    env_file:
      - ./config/wp.env

volumes:
  db_data: {}